# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

dm_ppmx_ct <- function(iter, burn, thin, nobs, treatments, PPMx, ncon, ncat, catvec, alpha, grid, Vwm, cohesion, CC, reuse, consim, similarity, calibration, coardegree, y, z, zpred, noprog, xcon, xcat, xconp, xcatp, npred, similparam, hP0_mu0, hP0_L0, hP0_nu0, hP0_S0, upd_hier, initbeta, hsp, mhtunepar, A, n_a, curr_cluster, card_cluster, ncluster_curr) {
    .Call('_treatppmx_dm_ppmx_ct', PACKAGE = 'treatppmx', iter, burn, thin, nobs, treatments, PPMx, ncon, ncat, catvec, alpha, grid, Vwm, cohesion, CC, reuse, consim, similarity, calibration, coardegree, y, z, zpred, noprog, xcon, xcat, xconp, xcatp, npred, similparam, hP0_mu0, hP0_L0, hP0_nu0, hP0_S0, upd_hier, initbeta, hsp, mhtunepar, A, n_a, curr_cluster, card_cluster, ncluster_curr)
}

prior_ppmx_core <- function(iter, burn, thin, nobs, PPMx, ncon, ncat, alpha, sigma, Vwm, cohesion, CC, consim, similarity, calibration, coardegree, xcon, similparam, curr_cluster, card_cluster, ncluster_curr) {
    .Call('_treatppmx_prior_ppmx_core', PACKAGE = 'treatppmx', iter, burn, thin, nobs, PPMx, ncon, ncat, alpha, sigma, Vwm, cohesion, CC, consim, similarity, calibration, coardegree, xcon, similparam, curr_cluster, card_cluster, ncluster_curr)
}

ran_mvnorm <- function(m, Sig, dim) {
    .Call('_treatppmx_ran_mvnorm', PACKAGE = 'treatppmx', m, Sig, dim)
}

ran_iwish <- function(nu, Sig, dim) {
    .Call('_treatppmx_ran_iwish', PACKAGE = 'treatppmx', nu, Sig, dim)
}

#' Similarity function
#'
#' Normal-normal-IG Similarity function with x following normal and m,v a normal-IG.
#' @param m0 location parameter
#' @param k0 shape gamma parameter
#' @param nu0 scale gamma parameter
#' @param s20 variance parameter
#' @param sumx cluster sum
#' @param sumx2 cluster squared sum
#' @param n number of observation in current cluster
#' @param DD logical if 1 Double Dipper similarity is employed
#' @param logout logical if 1 return log value
#' @export
gsimconNNIG <- function(m0, k0, nu0, s20, sumx, sumx2, n, DD, logout) {
    .Call('_treatppmx_gsimconNNIG', PACKAGE = 'treatppmx', m0, k0, nu0, s20, sumx, sumx2, n, DD, logout)
}

